/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/account/route'
import { Route as AuthenticatedWhatsappTemplatesIndexRouteImport } from './routes/_authenticated/whatsapp-templates/index'
import { Route as AuthenticatedWhatsappSessionsIndexRouteImport } from './routes/_authenticated/whatsapp-sessions/index'
import { Route as AuthenticatedWhatsappChatsIndexRouteImport } from './routes/_authenticated/whatsapp-chats/index'
import { Route as AuthenticatedWebFormsIndexRouteImport } from './routes/_authenticated/web-forms/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTransfersIndexRouteImport } from './routes/_authenticated/transfers/index'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedStatusesIndexRouteImport } from './routes/_authenticated/statuses/index'
import { Route as AuthenticatedStatisticsIndexRouteImport } from './routes/_authenticated/statistics/index'
import { Route as AuthenticatedSmsTemplatesIndexRouteImport } from './routes/_authenticated/sms-templates/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedSegmentsIndexRouteImport } from './routes/_authenticated/segments/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedHotelsIndexRouteImport } from './routes/_authenticated/hotels/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedEmailTemplatesIndexRouteImport } from './routes/_authenticated/email-templates/index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account/security'
import { Route as AuthenticatedAccountAppearanceRouteImport } from './routes/_authenticated/account/appearance'
import { Route as publicWebFormIframeUuidRouteImport } from './routes/(public)/web-form/iframe/$uuid'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappTemplatesIndexRoute =
  AuthenticatedWhatsappTemplatesIndexRouteImport.update({
    id: '/whatsapp-templates/',
    path: '/whatsapp-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappSessionsIndexRoute =
  AuthenticatedWhatsappSessionsIndexRouteImport.update({
    id: '/whatsapp-sessions/',
    path: '/whatsapp-sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappChatsIndexRoute =
  AuthenticatedWhatsappChatsIndexRouteImport.update({
    id: '/whatsapp-chats/',
    path: '/whatsapp-chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebFormsIndexRoute =
  AuthenticatedWebFormsIndexRouteImport.update({
    id: '/web-forms/',
    path: '/web-forms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersIndexRoute =
  AuthenticatedTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusesIndexRoute =
  AuthenticatedStatusesIndexRouteImport.update({
    id: '/statuses/',
    path: '/statuses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsIndexRoute =
  AuthenticatedStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSmsTemplatesIndexRoute =
  AuthenticatedSmsTemplatesIndexRouteImport.update({
    id: '/sms-templates/',
    path: '/sms-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSegmentsIndexRoute =
  AuthenticatedSegmentsIndexRouteImport.update({
    id: '/segments/',
    path: '/segments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelsIndexRoute =
  AuthenticatedHotelsIndexRouteImport.update({
    id: '/hotels/',
    path: '/hotels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailTemplatesIndexRoute =
  AuthenticatedEmailTemplatesIndexRouteImport.update({
    id: '/email-templates/',
    path: '/email-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountAppearanceRoute =
  AuthenticatedAccountAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const publicWebFormIframeUuidRoute = publicWebFormIframeUuidRouteImport.update({
  id: '/(public)/web-form/iframe/$uuid',
  path: '/web-form/iframe/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/account/appearance': typeof AuthenticatedAccountAppearanceRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hotels': typeof AuthenticatedHotelsIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/segments': typeof AuthenticatedSegmentsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sms-templates': typeof AuthenticatedSmsTemplatesIndexRoute
  '/statistics': typeof AuthenticatedStatisticsIndexRoute
  '/statuses': typeof AuthenticatedStatusesIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/transfers': typeof AuthenticatedTransfersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/web-forms': typeof AuthenticatedWebFormsIndexRoute
  '/whatsapp-chats': typeof AuthenticatedWhatsappChatsIndexRoute
  '/whatsapp-sessions': typeof AuthenticatedWhatsappSessionsIndexRoute
  '/whatsapp-templates': typeof AuthenticatedWhatsappTemplatesIndexRoute
  '/web-form/iframe/$uuid': typeof publicWebFormIframeUuidRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/account/appearance': typeof AuthenticatedAccountAppearanceRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hotels': typeof AuthenticatedHotelsIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/segments': typeof AuthenticatedSegmentsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sms-templates': typeof AuthenticatedSmsTemplatesIndexRoute
  '/statistics': typeof AuthenticatedStatisticsIndexRoute
  '/statuses': typeof AuthenticatedStatusesIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/transfers': typeof AuthenticatedTransfersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/web-forms': typeof AuthenticatedWebFormsIndexRoute
  '/whatsapp-chats': typeof AuthenticatedWhatsappChatsIndexRoute
  '/whatsapp-sessions': typeof AuthenticatedWhatsappSessionsIndexRoute
  '/whatsapp-templates': typeof AuthenticatedWhatsappTemplatesIndexRoute
  '/web-form/iframe/$uuid': typeof publicWebFormIframeUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/appearance': typeof AuthenticatedAccountAppearanceRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/email-templates/': typeof AuthenticatedEmailTemplatesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/hotels/': typeof AuthenticatedHotelsIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/segments/': typeof AuthenticatedSegmentsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sms-templates/': typeof AuthenticatedSmsTemplatesIndexRoute
  '/_authenticated/statistics/': typeof AuthenticatedStatisticsIndexRoute
  '/_authenticated/statuses/': typeof AuthenticatedStatusesIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/web-forms/': typeof AuthenticatedWebFormsIndexRoute
  '/_authenticated/whatsapp-chats/': typeof AuthenticatedWhatsappChatsIndexRoute
  '/_authenticated/whatsapp-sessions/': typeof AuthenticatedWhatsappSessionsIndexRoute
  '/_authenticated/whatsapp-templates/': typeof AuthenticatedWhatsappTemplatesIndexRoute
  '/(public)/web-form/iframe/$uuid': typeof publicWebFormIframeUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/account/appearance'
    | '/account/security'
    | '/customers/$customerId'
    | '/errors/$error'
    | '/account/'
    | '/appointments'
    | '/categories'
    | '/customers'
    | '/doctors'
    | '/email-templates'
    | '/help-center'
    | '/hotels'
    | '/organizations'
    | '/permissions'
    | '/reports'
    | '/roles'
    | '/segments'
    | '/services'
    | '/settings'
    | '/sms-templates'
    | '/statistics'
    | '/statuses'
    | '/tags'
    | '/transfers'
    | '/users'
    | '/web-forms'
    | '/whatsapp-chats'
    | '/whatsapp-sessions'
    | '/whatsapp-templates'
    | '/web-form/iframe/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/account/appearance'
    | '/account/security'
    | '/customers/$customerId'
    | '/errors/$error'
    | '/account'
    | '/appointments'
    | '/categories'
    | '/customers'
    | '/doctors'
    | '/email-templates'
    | '/help-center'
    | '/hotels'
    | '/organizations'
    | '/permissions'
    | '/reports'
    | '/roles'
    | '/segments'
    | '/services'
    | '/settings'
    | '/sms-templates'
    | '/statistics'
    | '/statuses'
    | '/tags'
    | '/transfers'
    | '/users'
    | '/web-forms'
    | '/whatsapp-chats'
    | '/whatsapp-sessions'
    | '/whatsapp-templates'
    | '/web-form/iframe/$uuid'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/account'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/account/appearance'
    | '/_authenticated/account/security'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/account/'
    | '/_authenticated/appointments/'
    | '/_authenticated/categories/'
    | '/_authenticated/customers/'
    | '/_authenticated/doctors/'
    | '/_authenticated/email-templates/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hotels/'
    | '/_authenticated/organizations/'
    | '/_authenticated/permissions/'
    | '/_authenticated/reports/'
    | '/_authenticated/roles/'
    | '/_authenticated/segments/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
    | '/_authenticated/sms-templates/'
    | '/_authenticated/statistics/'
    | '/_authenticated/statuses/'
    | '/_authenticated/tags/'
    | '/_authenticated/transfers/'
    | '/_authenticated/users/'
    | '/_authenticated/web-forms/'
    | '/_authenticated/whatsapp-chats/'
    | '/_authenticated/whatsapp-sessions/'
    | '/_authenticated/whatsapp-templates/'
    | '/(public)/web-form/iframe/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  publicWebFormIframeUuidRoute: typeof publicWebFormIframeUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-templates/': {
      id: '/_authenticated/whatsapp-templates/'
      path: '/whatsapp-templates'
      fullPath: '/whatsapp-templates'
      preLoaderRoute: typeof AuthenticatedWhatsappTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-sessions/': {
      id: '/_authenticated/whatsapp-sessions/'
      path: '/whatsapp-sessions'
      fullPath: '/whatsapp-sessions'
      preLoaderRoute: typeof AuthenticatedWhatsappSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-chats/': {
      id: '/_authenticated/whatsapp-chats/'
      path: '/whatsapp-chats'
      fullPath: '/whatsapp-chats'
      preLoaderRoute: typeof AuthenticatedWhatsappChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/web-forms/': {
      id: '/_authenticated/web-forms/'
      path: '/web-forms'
      fullPath: '/web-forms'
      preLoaderRoute: typeof AuthenticatedWebFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers/': {
      id: '/_authenticated/transfers/'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statuses/': {
      id: '/_authenticated/statuses/'
      path: '/statuses'
      fullPath: '/statuses'
      preLoaderRoute: typeof AuthenticatedStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics/': {
      id: '/_authenticated/statistics/'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms-templates/': {
      id: '/_authenticated/sms-templates/'
      path: '/sms-templates'
      fullPath: '/sms-templates'
      preLoaderRoute: typeof AuthenticatedSmsTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/segments/': {
      id: '/_authenticated/segments/'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AuthenticatedSegmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/': {
      id: '/_authenticated/hotels/'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof AuthenticatedHotelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-templates/': {
      id: '/_authenticated/email-templates/'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/appearance': {
      id: '/_authenticated/account/appearance'
      path: '/appearance'
      fullPath: '/account/appearance'
      preLoaderRoute: typeof AuthenticatedAccountAppearanceRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/(public)/web-form/iframe/$uuid': {
      id: '/(public)/web-form/iframe/$uuid'
      path: '/web-form/iframe/$uuid'
      fullPath: '/web-form/iframe/$uuid'
      preLoaderRoute: typeof publicWebFormIframeUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountAppearanceRoute: typeof AuthenticatedAccountAppearanceRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountAppearanceRoute: AuthenticatedAccountAppearanceRoute,
    AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
    AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedEmailTemplatesIndexRoute: typeof AuthenticatedEmailTemplatesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHotelsIndexRoute: typeof AuthenticatedHotelsIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSegmentsIndexRoute: typeof AuthenticatedSegmentsIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSmsTemplatesIndexRoute: typeof AuthenticatedSmsTemplatesIndexRoute
  AuthenticatedStatisticsIndexRoute: typeof AuthenticatedStatisticsIndexRoute
  AuthenticatedStatusesIndexRoute: typeof AuthenticatedStatusesIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedTransfersIndexRoute: typeof AuthenticatedTransfersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebFormsIndexRoute: typeof AuthenticatedWebFormsIndexRoute
  AuthenticatedWhatsappChatsIndexRoute: typeof AuthenticatedWhatsappChatsIndexRoute
  AuthenticatedWhatsappSessionsIndexRoute: typeof AuthenticatedWhatsappSessionsIndexRoute
  AuthenticatedWhatsappTemplatesIndexRoute: typeof AuthenticatedWhatsappTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedEmailTemplatesIndexRoute: AuthenticatedEmailTemplatesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHotelsIndexRoute: AuthenticatedHotelsIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSegmentsIndexRoute: AuthenticatedSegmentsIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSmsTemplatesIndexRoute: AuthenticatedSmsTemplatesIndexRoute,
  AuthenticatedStatisticsIndexRoute: AuthenticatedStatisticsIndexRoute,
  AuthenticatedStatusesIndexRoute: AuthenticatedStatusesIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedTransfersIndexRoute: AuthenticatedTransfersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebFormsIndexRoute: AuthenticatedWebFormsIndexRoute,
  AuthenticatedWhatsappChatsIndexRoute: AuthenticatedWhatsappChatsIndexRoute,
  AuthenticatedWhatsappSessionsIndexRoute:
    AuthenticatedWhatsappSessionsIndexRoute,
  AuthenticatedWhatsappTemplatesIndexRoute:
    AuthenticatedWhatsappTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  publicWebFormIframeUuidRoute: publicWebFormIframeUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
